# Generated by Django 4.2.5 on 2023-09-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strooptest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent', models.BooleanField(default=False, verbose_name='I have read the above information and consent to participate in this study.')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('NS', 'Prefer not to say')], max_length=2)),
                ('education', models.CharField(choices=[('HS', 'High School or less'), ('SC', 'Some College'), ('BD', "Bachelor's Degree"), ('MD', "Master's Degree"), ('PHD', 'PhD or higher')], max_length=3)),
                ('sleep_hours', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], verbose_name='How many hours of sleep did you get last night?')),
                ('caffeine_consumed', models.BooleanField(verbose_name='Have you consumed any caffeinated beverages today?')),
                ('alcohol_consumed', models.BooleanField(verbose_name='Have you consumed alcohol in the last 24 hours?')),
                ('medication', models.BooleanField(verbose_name='Are you currently taking any medication that affects attention or cognitive function?')),
                ('medication_details', models.TextField(blank=True, verbose_name='If yes, please specify:')),
                ('video_watch_frequency', models.CharField(choices=[('R', 'Rarely'), ('S', 'Sometimes'), ('F', 'Frequently'), ('V', 'Very frequently')], max_length=2, verbose_name='How often do you watch short videos (less than 1 minute) on platforms like TikTok, Instagram, etc.?')),
                ('stroop_experience', models.BooleanField(verbose_name='Have you ever participated in a Stroop Test before?')),
                ('current_mood', models.CharField(choices=[('VN', 'Very Negative'), ('N', 'Negative'), ('NE', 'Neutral'), ('P', 'Positive'), ('VP', 'Very Positive')], max_length=2, verbose_name='How would you rate your current mood?')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='StroopTest',
        ),
    ]
