# Generated by Django 4.2.5 on 2023-09-06 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strooptest', '0002_questionnaire_delete_strooptest'),
    ]

    operations = [
        migrations.CreateModel(
            name='StroopTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(max_length=50)),
                ('response_time', models.FloatField()),
                ('is_correct', models.BooleanField()),
                ('word_color_pair', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strooptest.questionnaire')),
            ],
        ),
    ]
