# Generated by Django 4.2.5 on 2023-09-11 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strooptest', '0003_strooptest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='age',
            field=models.IntegerField(verbose_name='Age (Yoshingiz nechida?)'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='alcohol_consumed',
            field=models.BooleanField(verbose_name="Have you consumed alcohol in the last 24 hours? (Siz oxirgi 24 soatda alkogol iste'mol qildingizmi?)"),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='caffeine_consumed',
            field=models.BooleanField(verbose_name="Have you consumed any caffeinated beverages today? (Siz bugun kofeinli ichimlik iste'mol qildingizmi?)"),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='consent',
            field=models.BooleanField(default=False, verbose_name="I have read the above information and consent to participate in this study. (Men yuqoridagi ma'lumotni o'qib chiqdim va bu tadqiqotda ishtirok etishga rozimanman.)"),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='current_mood',
            field=models.CharField(choices=[('VN', 'Very Negative (Juda salbiy)'), ('N', 'Negative (Salbiy)'), ('NE', 'Neutral (Noaniq)'), ('P', 'Positive (Ijobiy)'), ('VP', 'Very Positive (Juda ijobiy)')], max_length=2, verbose_name='How would you rate your current mood? (Qanday darajada joriy kayfiyatingizga baho berishingiz mumkin?)'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='education',
            field=models.CharField(choices=[('HS', 'High School or less (Oliy maktab yoki undan pastroq)'), ('SC', 'Some College (Bazi kollej)'), ('BD', "Bachelor's Degree (Bakalavr darajasi)"), ('MD', "Master's Degree (Magistr darajasi)"), ('PHD', 'PhD or higher (PhD yoki undan yuqori)')], max_length=3, verbose_name="Education Level (Ma'lumotingiz)"),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email (Elektron pochta)'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='gender',
            field=models.CharField(choices=[('M', 'Male (Erkak)'), ('F', 'Female (Ayol)'), ('NB', 'Non-Binary (Noaniq)'), ('NS', 'Prefer not to say (Aytishni xohlamayman)')], max_length=2, verbose_name='Gender (Jinsingiz)'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='medication',
            field=models.BooleanField(verbose_name="Are you currently taking any medication that affects attention or cognitive function? (Siz hozirda diqqat yoki kognitiv funksiyani ta'sir qiladigan dori vositalarini qabul qilyapsizmi?)"),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='medication_details',
            field=models.TextField(blank=True, verbose_name="If yes, please specify: (Agar ha, iltimos ko'rsating:)"),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='sleep_hours',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')], verbose_name='How many hours of sleep did you get last night? (Siz kechqurun nechta soat uxladingiz?)'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='stroop_experience',
            field=models.BooleanField(verbose_name='Have you ever participated in a Stroop Test before? (Siz avvalgi Stroop Testida qatnashganmisiz?)'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='video_watch_frequency',
            field=models.CharField(choices=[('R', 'Rarely (Kamchilik)'), ('S', "Sometimes (Ba'zan)"), ('F', 'Frequently (Tez-tez)'), ('V', "Very frequently (Juda ko'p)")], max_length=2, verbose_name="How often do you watch short videos (less than 1 minute) on platforms like TikTok, Instagram, etc.? (Siz TikTok, Instagram kabi platformalarda (1 daqiqadan kamroq) qisqa videolarni qanchalik tez-tez ko'rasiz?)"),
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=10)),
                ('avg_accuracy', models.FloatField()),
                ('avg_response_time', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strooptest.questionnaire')),
            ],
        ),
    ]
