# Generated by Django 4.2.5 on 2023-09-11 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strooptest', '0004_alter_questionnaire_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email (Elektron pochta oldin ro'yxatdan o'tilgan)"),
        ),
    ]
